# https://github.com/numtide/treefmt-nix/blob/main/examples

[formatter.clang-format]
command = "clang-format"
excludes = []
includes = [
  "*.c",
  "*.cc",
  "*.cpp",
  "*.h",
  "*.hh",
  "*.hpp",
  "*.glsl",
  "*.vert",
  ".tesc",
  ".tese",
  ".geom",
  ".frag",
  ".comp",
]
options = ["-i"]

[formatter.clang-tidy]
command = "clang-tidy"
excludes = []
includes = [
  "*.c",
  "*.cc",
  "*.cpp",
  "*.h",
  "*.hh",
  "*.hpp",
  "*.glsl",
  "*.vert",
  ".tesc",
  ".tese",
  ".geom",
  ".frag",
  ".comp",
]
options = ["--fix", "--quiet"]

[formatter.cmake-format]
command = "cmake-format"
excludes = []
includes = ["*.cmake", "CMakeLists.txt"]
options = ["--in-place"]

[formatter.nixfmt]
command = "nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[formatter.prettier]
command = "prettier"
excludes = []
includes = [
  "*.cjs",
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.json5",
  "*.jsx",
  "*.md",
  "*.mdx",
  "*.mjs",
  "*.scss",
  "*.ts",
  "*.tsx",
  "*.vue",
  "*.yaml",
  "*.yml",
]
options = ["--write"]

[formatter.ruff-check]
command = "ruff"
excludes = []
includes = ["*.py", "*.pyi"]
options = ["check", "--fix"]

[formatter.ruff-format]
command = "ruff"
excludes = []
includes = ["*.py", "*.pyi"]
options = ["format"]

[formatter.taplo]
command = "taplo"
excludes = []
includes = ["*.toml"]
options = ["format"]
